### ISSUE TITLE
configlet lint: ignore git-ignored files?

### ISSUE THREAD

**Issue by stkent** [exercism/v2-configlet#108]
The current version of `configlet` reports the following lint errors on the Java track:

```
$ configlet lint .
-> An implementation for '.idea' was found, but config.json does not reference this exercise.
-> An implementation for '.gradle' was found, but config.json does not reference this exercise.
-> The implementation for '.idea' is missing an example solution.
-> The implementation for '.gradle' is missing an example solution.
-> The implementation for '.gradle' is missing a test suite.
```

The directories found here are local-only (ignored by git). Is there a way to have `configlet lint` operate only on non-git-ignored files?

**Comment by tleen** [comment]
Or perhaps ignore non-standard dotfiles?

**Comment by stkent** [comment]
(Those are dotdirs, if that makes any difference 😄)

**Comment by tleen** [comment]
Right, dot-thingies :laughing:

**Comment by Insti** [comment]
There used to be an `ignore` section in `config.json` for this.

Update: It was removed. https://github.com/exercism/configlet/commit/bcc77a32509dcea1e0ef0a8389791abc6c3cc94d

**Comment by kytrinyx** [comment]
> There used to be an ignore section in `config.json` for this.

For what it's worth, it was not for this, though I would understand it if it were used for that.

The origin of `ignore` was that we had exercises living in the root dir of the track, and so we needed to track what directories in the root that were part of the git repository, but which were _not_ exercises (e.g. `docs`, `img`, `test`, `bin`, etc). Now that exercises live under `exercises/` the ignore key is not needed.

If we ignore dotfiles and dot directories then we should probably also ignore hidden files on Windows. I think that would probably be a reasonable approach.

I think I slightly prefer the idea of ignoring what's being ignored by Git, however that has a level of complexity that I'm not comfortable with, since we would need to look at `.gitignore`, `.git/info/exclude`, and (presumably) the entire PATH up to home to find any global ignores.

If Git gives us a way to list files that are ignored without having to specify which ignore file to listen to, then I would be more comfortable with that approach.

**Comment by stkent** [comment]
Maybe something like https://stackoverflow.com/a/39064584/2911458?

**Comment by Insti** [comment]
> Now that exercises live under exercises/ the ignore key is not needed.

Removing it  was certainly reasonable.

>  Maybe something like https://stackoverflow.com/a/39064584/2911458?

Does it need to be that complicated and depend on `git`? Could we just put an `ignored` section back and explicitly list the files/paths/patterns to ignore?

**Comment by kytrinyx** [comment]
Just to confirm: `.idea` and `.gradle` are not committed to the repository, right?

If not, then I would prefer not to have to add anything to the `config.json` file about it, since there's no reason why anyone looking at the config should have to know that people have these directories locally.

On the other hand, it seems like these would be language-specific enough that they'd appear in the `.gitignore` file. I don't think we need to rely on `git`, even if we read the `.gitignore` file in the Track repository.

Given what I know about this so far, my preference would be to not rely on `.git/info/exclude` or any files that `git` ignores, but simply to read in the `.gitignore` file that is committed to the repository.

**Comment by stkent** [comment]
> Just to confirm: `.idea` and `.gradle` are not committed to the repository, right?

Correct. The `.idea` folder is specific to contributors who use IntelliJ, but the `.gradle` folder should appear for any contributor who chooses to run track-wide tests.

**Comment by nywilken** [comment]
@kytrinyx @stkent is this something that could be easily resolved if we ignored directory names and files that are hidden (dot files), or that begin with an underscore when traversing the track's exercise directory [#L48](https://github.com/exercism/configlet/blob/master/track/track.go#L48)? 

Or are we looking for  a more robust solution to ignoring files and directories?

**Comment by stkent** [comment]
That would work for the Java track's specific use-case, but I'm not sure what @kytrinyx has in mind r.e. generality of solution.

**Comment by kytrinyx** [comment]
> That would work for the Java track's specific use-case

I'm OK with generalizing to say that no exercise slugs should start with a `.` or a `_`, which would solve this particular issue for the Java track, and would possibly be "good enough" to let us work around a lot of other potential issues that could come up.

I'm more comfortable with the simple-but-not-quite-generalized solution for now, with the potential of re-evaluating a more complex solution should a similar problem arise later.

So: in conclusion—unless someone has some really strong arguments against it—I would suggest that we update configlet to ignore any directories in the exercises directory that start with a `.` or a `_`.
