### ISSUE TITLE
Mac build reporting duplicated guid when win or Linux are not 

### ISSUE THREAD

**Issue by masters3d** [exercism/v2-configlet#124]
https://github.com/exercism/typescript/pull/161

**Comment by kytrinyx** [comment]
The Mac build on Circle CI appears to build the project into a directory with a non-standard name,
'project', which means that the configlet lint command tells the Exercism UUID API endpoint that
it's checking the UUIDs of the 'project' track, rather than the typescript track.

As a result, the UUID API reports that the UUIDs are duplicates.

I'll submit a PR that fixes this to the typescript track repo.
