### ISSUE TITLE
generate: <track>/<exercise>/.meta/description.md not replacing Spec.description

### ISSUE THREAD

**Issue by tleen** [exercism/v2-configlet#65]
Not sure I understand the instructions entirely via the docs's [README readme](https://github.com/exercism/docs/blob/master/language-tracks/exercises/anatomy/readmes.md). 

Under "Description":
> Having said that, each track is free to write a more specific description if they want to, placing it either in the .meta/description.md, or directly into the README template.

I can't seem to get configlet to override the specification description using a `.meta/description.md` file inside of a track exercise. `.meta/hints.md` is included no problem. I am using configlet v3.4.0.

**Comment by nywilken** [comment]
@tleen the supported override path for `.meta/description.md` is within the root directory of an exercise `e.g /numbers/exercises/two/.meta`. 

Is this the path convention you are using? If so, it may be a bug on the configlet end. Looking at the configlet code I see what might be an issue, but I need to verify. 

Could you provide the command including the flags, if any, along with a sample of the directory structure for the track and problem-specifications directory you are running configlet against.  Thanks

**Comment by tleen** [comment]
I have my [problem-specifications fork](https://github.com/tleen/problem-specifications), as a peer with my [fork of the go track](https://github.com/tleen/xgo) in a directory. Both are at current master.

In my xgo directory I do this:

```text
$ ls exercises/largest-series-product/.meta/
description.md  gen.go  hints.md

$ cat exercises/largest-series-product/.meta/description.md 
THIS IS A DESCRIPTION INSERT

$ cat exercises/largest-series-product/.meta/hints.md 
These are hints for largest series product.

$ configlet version
configlet version 3.4.0

$ git checkout exercises/largest-series-product/README.md

$ git diff exercises/largest-series-product/README.md

$ configlet generate . --only largest-series-product

$ git diff exercises/largest-series-product/README.md

diff --git a/exercises/largest-series-product/README.md b/exercises/largest-series-product/README.md
index 8bc5c5e..1378fcc 100644
--- a/exercises/largest-series-product/README.md
+++ b/exercises/largest-series-product/README.md
@@ -13,6 +13,9 @@ in the input; the digits need not be *numerically consecutive*.
 For the input `'73167176531330624919225119674426574742355349194934'`,
 the largest product for a series of 6 digits is 23520.
 
+These are hints for largest series product.
+
+
 ## Running the tests
 
 To run the tests run the command `go test` from within the exercise directory.
```

I would have figured "THIS IS A DESCRIPTION INSERT" would have replaced the entire top of the file, but it only looks like the `hints.md` made it into the README.

**Comment by nywilken** [comment]
Thanks for the detailed reproduction steps. So looking at the problem I see that configlet is throwing an error because it can not find the file `~/exercism/xgo/exercises/largest-series-product/.meta/metadata.yml`, which causes it to default to the contents within the problem-specifications directory. 

The hints override works because it is handled differently then the spec description. This is a bug that should be addressed within Configlet and within the documentation. 

In the meantime, to fix this issue you can copy the metadata.yml from the problem-specifications directory into your xgo directory - please follow the steps, I took, below and let me know if you are able to successfully override the description. 

```
# Copy the metadata.yml from problem-specifications directory into the xgo directory
cp ../problem-specifications/exercises/largest-series-product/metadata.yml exercises/largest-series-product/.meta

$ ls exercises/largest-series-product/.meta                                    
description.md  gen.go  hints.md  metadata.yml

$ configlet generate . --only largest-series-product

$ gd exercises/largest-series-product/README.md 
diff --git a/exercises/largest-series-product/README.md b/exercises/largest-series-product/README.md
index 8bc5c5e..9653450 100644
--- a/exercises/largest-series-product/README.md
+++ b/exercises/largest-series-product/README.md
@@ -1,17 +1,9 @@
 # Largest Series Product
 
-Given a string of digits, calculate the largest product for a contiguous
-substring of digits of length n.
+THIS IS A DESCRIPTION INSERT
 
-For example, for the input `'1027839564'`, the largest product for a
-series of 3 digits is 270 (9 * 5 * 6), and the largest product for a
-series of 5 digits is 7560 (7 * 8 * 3 * 9 * 5).
+These are hints for largest series product.
 
-Note that these series are only required to occupy *adjacent positions*
-in the input; the digits need not be *numerically consecutive*.
-
-For the input `'73167176531330624919225119674426574742355349194934'`,
-the largest product for a series of 6 digits is 23520.
 
 ## Running the tests
```

**Comment by kytrinyx** [comment]
I've made the assumption that if you override one of the metadata files, you override both. I can see now that this was not a particularly good assumption. (Sorry about the confusion!)

On a secondary note, I'm going to update the documentation to not encourage people to put things directly into the README, since v2 uses the metadata and description files in various places, and we would lose any overrides.

**Comment by tleen** [comment]
@nywilken you nailed it :+1: . Copying in the `problem-specification/exercises/largest-series-product/metadata.yml` into the `xgo/exercises/largest-series-product/metadata.yml` then re-running the configlet generate did fix the problem.

In most situations where I see tweaking the README contents via the `.meta/description.md` file would not need any modifications to the `metadata.yml`. It is mostly around weird situational discrepancies. For the most part they are quickfixes till we can modify the exercises themselves to more accurately reflect the problem-specifications data.

**Comment by kytrinyx** [comment]
> In most situations where I see tweaking the README contents via the .meta/description.md file would not need any modifications to the metadata.yml.

Agreed—for some reason I think I started out thinking about local metadata as something you'd only do when people create a track-specific exercise. Then at some point I realized that this would make it easy to override the description where appropriate, and my brain never connected the dots.

**Comment by nywilken** [comment]
@kytrinyx @tleen I started working on fixing this issue, but I think I might've taken the wrong path. 

Currently, the file `metadata.yml` is required for overwriting the readme description, which is what I started to enforce after reading
>On a secondary note, I'm going to update the documentation to not encourage people to put things directly into the README, since v2 uses the metadata and description files in various places, and we would lose any overrides

But I think I might have misunderstood that sentence  and should actually be decoupling description.md from metadata.yml, to behave more like hints.md.

Can I get your thoughts on what the expected behavior should be so that my changes work nicely with the V2 changes. Thanks!

**Comment by tleen** [comment]
I generally expected that if there was a `description.md` file in the exercise meta it would be placed in the `{{ .Spec.Description -}}` value of the template, independently of any other files in there.

**Comment by nywilken** [comment]
@tleen thanks for the quick response - very helpful. I'll refactor the solution and give things a test.

**Comment by kytrinyx** [comment]
> I think I might have misunderstood that sentence and should actually be decoupling description.md from metadata.yml, to behave more like hints.md.

Agreed, these should be decoupled. It was my bad assumption that coupled them in the first place.

**Comment by nywilken** [comment]
👍  I should have a PR out shortly for review - been a little behind on commits. But definitely thanks for clarifying.
