### ISSUE TITLE
lint alumnus key in maintainers file

### ISSUE THREAD

**Issue by robphoenix** [exercism/v2-configlet#75]
https://github.com/exercism/v2-feedback/issues/81 has suggested the `alumnus` key in the maintainers.json file be changed to be either `null` or one of 3 values: ("alumnum", "alumnus", "alumna").

We should probably lint this to ensure only these values are used.

**Comment by kytrinyx** [comment]
If someone wants to pick this one up, the key place to start is the `cmd/lint.go` file, with the corresponding tests in `cmd/lint_test.go`. Holler if you have questions (all questions are good, because then we can fix our documentation so the next person doesn't have to wonder about the same thing).
